trigger:
- main  # Измените на нужную ветку

pool:
  vmImage: 'windows-latest'  # Используем Windows для выполнения скриптов PowerShell

variables:
  buildConfiguration: 'Release'
  versionStampFile: 'VersionStamp.txt'
  targetDirectory: 'C:\\IT'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m venv venv
    venv\Scripts\activate
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    venv\Scripts\activate
    pytest
  displayName: 'Run tests'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- powershell: |
    .\copyArtifacts.ps1 -buildArtifactStagingDirectory $(Build.ArtifactStagingDirectory) -targetDirectory $(targetDirectory) -versionStampFile $(versionStampFile)
  displayName: 'Update and copy VersionStamp.txt'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: SendEmail@1
  inputs:
    To: 'artemegorov2517@gmail.com'
    From: 'soldierwaat@gmail.com'
    Subject: 'Build Status'
    BodyAsHtml: false
    AddAttachment: false
